name: Check Markdown links

on:
  push:
    paths:
      - '**.md'
  pull_request:
    branches: [main]
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'true'
        use-verbose-mode: 'true'
        check-modified-files-only: 'true'
        config-file: '.github/workflows/markdown-link-check-config.json'
        base-branch: 'main'
